[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'Wombat'

[[plugins]]
repo = 'glidenote/serverspec-snippets'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'pearofducks/ansible-vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'markcornick/vim-terraform'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'mmozuras/vim-github-comment'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'superbrothers/vim-vimperator'

[[plugins]]
repo = 'garyburd/go-explorer'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'rhysd/unite-redpen.vim'
