#!/usr/bin/env perl

sub paste_primary {
    my ($self) = @_;
    my $o = $self->locale_encode($self->selection);
    if ($o) {
        $self->tt_write($o);
    } else {
        open my $fh, '-|', qw/xsel/ or die $!;
        while (<$fh>) {
            $self->tt_write($_);
        }
        close $fh or warn "status: $?";
    }
    ()
}

sub paste_clipboard {
    my ($self) = @_;
    open my $fh, '-|', qw/xsel -b/ or die $!;
    while (<$fh>) {
        $self->tt_write($_);
    }
    close $fh or warn "status: $?";
    ()
}

sub on_user_command {
    my ($self, $cmd) = @_;

    if ($cmd eq "x-selection:paste_primary") {
        # $self->tt_write('[p]');
        $self->paste_primary;
    }

    if ($cmd eq "x-selection:paste_clipboard") {
        # $self->tt_write('[c]')
        $self->paste_clipboard;
    }
    ()
}

